import 'dart:io';

import 'package:drift/drift.dart' hide Column;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../audit/audit_service.dart';
import '../database/app_database.dart';
import '../auth/auth_service.dart';

/// Centralized report generation service.
/// All reports share: Company header, user info, date, title, professional layout.
class ReportService {
  ReportService._();

  static final _dateFormat = DateFormat('dd-MM-yyyy hh:mm a');
  static pw.MemoryImage? _crescentBrandImage;

  // ─── Calibration Report ──────────────────────────────────────────────────

  static Future<void> printCalibrationReport({
    required BuildContext context,
    required String deviceId,
    required String deviceType, // 'ph' or 'ec'
    required String mode, // '3' or '5'
    required List<CalibrationRow> rows,
    String? probe,
  }) async {
    final company = await AppDatabase.instance.getCompanyDetails();
    final user = AuthService.instance.currentUser;
    final now = DateTime.now();
    final brandImage = await _loadCrescentBrandImage();

    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) =>
            _buildHeader(company, 'Calibration Report', now, brandImage),
        footer: (ctx) => _buildFooter(ctx, user, brandImage),
        build: (ctx) => [
          pw.SizedBox(height: 16),
          // Device Info
          _infoRow('Device ID', deviceId),
          _infoRow('Device Type', deviceType.toUpperCase()),
          _infoRow('Mode', '$mode Point Calibration'),
          if (probe != null && probe.isNotEmpty) _infoRow('Probe', probe),
          _infoRow('Calibration Date', _dateFormat.format(now)),
          _infoRow('Generated By', user?.name ?? 'N/A'),
          pw.SizedBox(height: 16),

          // Calibration Table
          pw.TableHelper.fromTextArray(
            context: ctx,
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: 9,
              color: PdfColors.white,
            ),
            headerDecoration: const pw.BoxDecoration(color: PdfColor(0.2, 0.4, 0.7)),
            cellStyle: const pw.TextStyle(fontSize: 8),
            cellPadding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
            headerAlignments: {
              0: pw.Alignment.center,
              1: pw.Alignment.center,
              2: pw.Alignment.center,
              3: pw.Alignment.center,
              4: pw.Alignment.center,
              5: pw.Alignment.center,
            },
            cellAlignments: {
              0: pw.Alignment.center,
              1: pw.Alignment.center,
              2: pw.Alignment.center,
              3: pw.Alignment.center,
              4: pw.Alignment.center,
              5: pw.Alignment.center,
            },
            headers: [
              deviceType == 'ec' ? 'EC' : 'pH',
              '${deviceType == 'ec' ? 'EC' : 'pH'} After Cal',
              'Slope',
              'Temp (°C)',
              'mV',
              'Date & Time',
            ],
            data: rows.asMap().entries.map((entry) {
              final idx = entry.key;
              final r = entry.value;
              return [
                r.val.toString(),
                r.valAfterCal?.toStringAsFixed(2) ?? '--',
                idx == 0 ? '--' : (r.slope?.toStringAsFixed(4) ?? '--'),
                r.temp?.toStringAsFixed(1) ?? '--',
                r.mv?.toStringAsFixed(2) ?? '--',
                r.time != null ? _dateFormat.format(r.time!) : '--',
              ];
            }).toList(),
          ),

          pw.SizedBox(height: 24),
          _remarksSection(),
        ],
      ),
    );
    final savedPath = await _saveAndRecord(
      pdf: pdf,
      fileName: 'Calibration_Report_$deviceId',
      reportType: 'calibration',
      deviceId: deviceId,
      deviceType: deviceType,
    );
    if (context.mounted) {
      await _showPrintPreview(context, pdf, savedPath.$2);
    }
  }

  // ─── Logs Report ─────────────────────────────────────────────────────────

  static Future<void> printLogsReport({
    required BuildContext context,
    required String deviceId,
    required String deviceType,
    required List<Log> logs,
    String? product,
    String? batchNo,
    String? arNo,
  }) async {
    final company = await AppDatabase.instance.getCompanyDetails();
    final user = AuthService.instance.currentUser;
    final now = DateTime.now();
    final brandImage = await _loadCrescentBrandImage();

    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) => _buildHeader(company, 'Log Report', now, brandImage),
        footer: (ctx) => _buildFooter(ctx, user, brandImage),
        build: (ctx) => [
          pw.SizedBox(height: 16),
          // Device + Product Info
          _infoRow('Device ID', deviceId),
          _infoRow('Device Type', deviceType.toUpperCase()),
          _infoRow('Product Name', (product?.trim().isNotEmpty ?? false) ? product!.trim() : '--'),
          _infoRow('Batch No', (batchNo?.trim().isNotEmpty ?? false) ? batchNo!.trim() : '--'),
          _infoRow('AR No', (arNo?.trim().isNotEmpty ?? false) ? arNo!.trim() : '--'),
          _infoRow('Total Entries', '${logs.length}'),
          _infoRow('Generated By', user?.name ?? 'N/A'),
          pw.SizedBox(height: 16),

          // Logs Table
          pw.TableHelper.fromTextArray(
            context: ctx,
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: 9,
              color: PdfColors.white,
            ),
            headerDecoration: const pw.BoxDecoration(color: PdfColor(0.2, 0.5, 0.3)),
            cellStyle: const pw.TextStyle(fontSize: 8),
            cellPadding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
            headerAlignments: {
              0: pw.Alignment.center,
              1: pw.Alignment.center,
              2: pw.Alignment.center,
              3: pw.Alignment.center,
              4: pw.Alignment.centerLeft,
              5: pw.Alignment.centerLeft,
              6: pw.Alignment.centerLeft,
            },
            cellAlignments: {
              0: pw.Alignment.center,
              1: pw.Alignment.center,
              2: pw.Alignment.center,
              3: pw.Alignment.center,
              4: pw.Alignment.centerLeft,
              5: pw.Alignment.centerLeft,
              6: pw.Alignment.centerLeft,
            },
            headers: [
              '#',
              deviceType == 'ec' ? 'EC' : 'pH',
              'Temp (°C)',
              'Date & Time',
              'Product',
              'Batch No.',
              'AR No.',
            ],
            data: logs.asMap().entries.map((entry) {
              final idx = entry.key;
              final l = entry.value;
              return [
                '${idx + 1}',
                l.val.toStringAsFixed(2),
                l.temp.toStringAsFixed(1),
                _dateFormat.format(l.createdAt),
                (l.product?.trim().isNotEmpty ?? false) ? l.product!.trim() : '--',
                (l.batchNo?.trim().isNotEmpty ?? false) ? l.batchNo!.trim() : '--',
                (l.arNo?.trim().isNotEmpty ?? false) ? l.arNo!.trim() : '--',
              ];
            }).toList(),
          ),
          pw.SizedBox(height: 24),
          _remarksSection(),
        ],
      ),
    );
    final savedPath = await _saveAndRecord(
      pdf: pdf,
      fileName: 'Log_Report_$deviceId',
      reportType: 'log',
      deviceId: deviceId,
      deviceType: deviceType,
    );
    if (context.mounted) {
      await _showPrintPreview(context, pdf, savedPath.$2);
    }
  }

  // ─── Graph Report ────────────────────────────────────────────────────────

  static Future<void> printGraphReport({
    required BuildContext context,
    required String deviceId,
    required String deviceType,
    required Uint8List graphImage,
    required List<Log> logs,
    String? product,
    String? batchNo,
  }) async {
    final company = await AppDatabase.instance.getCompanyDetails();
    final user = AuthService.instance.currentUser;
    final now = DateTime.now();
    final brandImage = await _loadCrescentBrandImage();

    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) =>
            _buildHeader(company, 'Graph Report', now, brandImage),
        footer: (ctx) => _buildFooter(ctx, user, brandImage),
        build: (ctx) {
          final image = pw.MemoryImage(graphImage);
          return [
            pw.SizedBox(height: 16),
            _infoRow('Device ID', deviceId),
            _infoRow('Device Type', deviceType.toUpperCase()),
            if (product != null && product.isNotEmpty)
              _infoRow('Product', product),
            if (batchNo != null && batchNo.isNotEmpty)
              _infoRow('Batch No', batchNo),
            _infoRow('Data Points', '${logs.length}'),
            _infoRow('Generated By', user?.name ?? 'N/A'),
            pw.SizedBox(height: 16),

            // Graph Image
            pw.Container(
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
                borderRadius: pw.BorderRadius.circular(4),
              ),
              padding: const pw.EdgeInsets.all(8),
              child: pw.Image(image, fit: pw.BoxFit.contain),
            ),

            pw.SizedBox(height: 24),
            _remarksSection(),
          ];
        },
      ),
    );
    final savedPath = await _saveAndRecord(
      pdf: pdf,
      fileName: 'Graph_Report_$deviceId',
      reportType: 'graph',
      deviceId: deviceId,
      deviceType: deviceType,
    );
    if (context.mounted) {
      await _showPrintPreview(context, pdf, savedPath.$2);
    }
  }

  // ─── Shared Builders ────────────────────────────────────────────────────

  /// Standard report header: Company name, logo area, report title, date
  static pw.Widget _buildHeader(
    CompanyDetail? company,
    String reportTitle,
    DateTime generatedAt,
    pw.MemoryImage? brandImage,
  ) {
    return pw.Column(
      children: [
        // Company Header Row
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // Company Info
            pw.Expanded(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    company?.companyName.isNotEmpty == true
                        ? company!.companyName
                        : 'Crestant Scientific Pvt Ltd',
                    style: pw.TextStyle(
                      fontSize: 16,
                      fontWeight: pw.FontWeight.bold,
                      color: const PdfColor(0.15, 0.3, 0.6),
                    ),
                  ),
                  if (company?.address.isNotEmpty == true)
                    pw.Text(
                      company!.address,
                      style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
                    ),
                  pw.SizedBox(height: 2),
                  pw.Row(
                    children: [
                      if (company?.phone.isNotEmpty == true)
                        pw.Text(
                          'Tel: ${company!.phone}',
                          style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey600),
                        ),
                      if (company?.phone.isNotEmpty == true &&
                          company?.email.isNotEmpty == true)
                        pw.Text('  |  ',
                            style: const pw.TextStyle(
                                fontSize: 7, color: PdfColors.grey400)),
                      if (company?.email.isNotEmpty == true)
                        pw.Text(
                          'Email: ${company!.email}',
                          style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey600),
                        ),
                    ],
                  ),
                  if (company?.website.isNotEmpty == true)
                    pw.Text(
                      company!.website,
                      style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey600),
                    ),
                  if (company?.gstNo.isNotEmpty == true)
                    pw.Text(
                      'GST: ${company!.gstNo}',
                      style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey600),
                    ),
                ],
              ),
            ),

            // Report Title + Date + Brand (right side)
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                if (brandImage != null)
                  pw.Container(
                    margin: const pw.EdgeInsets.only(bottom: 6),
                    height: 26,
                    child: pw.Image(brandImage, fit: pw.BoxFit.contain),
                  ),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                  decoration: pw.BoxDecoration(
                    color: const PdfColor(0.15, 0.3, 0.6),
                    borderRadius: pw.BorderRadius.circular(4),
                  ),
                  child: pw.Text(
                    reportTitle,
                    style: pw.TextStyle(
                      fontSize: 11,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.white,
                    ),
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Date: ${_dateFormat.format(generatedAt)}',
                  style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
                ),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: const PdfColor(0.15, 0.3, 0.6), thickness: 1.5),
      ],
    );
  }

  /// Standard report footer: page number, generated-by info
  static pw.Widget _buildFooter(
      pw.Context ctx, User? user, pw.MemoryImage? brandImage) {
    return pw.Column(
      children: [
        pw.Divider(color: PdfColors.grey300, thickness: 0.5),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by: ${user?.name ?? 'N/A'} (${user?.role ?? 'N/A'})',
              style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey500),
            ),
            pw.Row(
              children: [
                if (brandImage != null)
                  pw.Container(
                    margin: const pw.EdgeInsets.only(right: 8),
                    height: 10,
                    child: pw.Image(brandImage, fit: pw.BoxFit.contain),
                  ),
                pw.Text(
                  'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
                  style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey500),
                ),
              ],
            ),
          ],
        ),
      ],
    );
  }

  static Future<pw.MemoryImage?> _loadCrescentBrandImage() async {
    if (_crescentBrandImage != null) return _crescentBrandImage;
    final ByteData bytes = await rootBundle.load('assets/crescent.png');
    _crescentBrandImage = pw.MemoryImage(bytes.buffer.asUint8List());
    return _crescentBrandImage;
  }

  /// Info key-value row
  static pw.Widget _infoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(
              label,
              style: pw.TextStyle(
                fontSize: 9,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey700,
              ),
            ),
          ),
          pw.Text(': ', style: const pw.TextStyle(fontSize: 9)),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 9)),
          ),
        ],
      ),
    );
  }

  /// Remarks / Notes section placeholder
  static pw.Widget _remarksSection() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Remarks / Notes:',
          style: pw.TextStyle(
            fontSize: 10,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey700,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Container(
          width: double.infinity,
          height: 60,
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
            borderRadius: pw.BorderRadius.circular(4),
          ),
        ),
      ],
    );
  }

  /// Save PDF to disk and record in DB. Returns (filePath, displayName).
  static Future<(String, String)> _saveAndRecord({
    required pw.Document pdf,
    required String fileName,
    required String reportType,
    required String deviceId,
    required String deviceType,
  }) async {
    final bytes = await pdf.save();

    // Save to documents/reports/
    final docsDir = await getApplicationDocumentsDirectory();
    final reportsDir = Directory(p.join(docsDir.path, 'iot_lab_reports'));
    if (!reportsDir.existsSync()) reportsDir.createSync(recursive: true);

    final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    final fullName = '${fileName}_$timestamp.pdf';
    final filePath = p.join(reportsDir.path, fullName);
    final file = File(filePath);
    await file.writeAsBytes(bytes);

    // Record in DB
    final user = AuthService.instance.currentUser;
    await AppDatabase.instance.insertReportFile(ReportFilesCompanion(
      fileName: Value(fullName),
      reportType: Value(reportType),
      deviceId: Value(deviceId),
      deviceType: Value(deviceType),
      filePath: Value(filePath),
      fileSize: Value(bytes.length),
      generatedBy: Value(user?.name ?? 'Unknown'),
      format: const Value('pdf'),
    ));
    await AuditService.instance.log(
      category: AuditService.catReport,
      action: 'generate',
      entityType: 'report',
      entityId: fullName,
      details: {
        'reportType': reportType,
        'deviceId': deviceId,
        'deviceType': deviceType,
      },
    );

    return (filePath, fullName);
  }

  /// Show print preview dialog
  static Future<void> _showPrintPreview(
    BuildContext context,
    pw.Document pdf,
    String filename,
  ) async {
    final bytes = await pdf.save();
    if (!context.mounted) return;

    await Navigator.of(context).push(
      MaterialPageRoute(
        builder: (_) => Scaffold(
          appBar: AppBar(
            title: Text(filename),
            actions: [
              IconButton(
                icon: const Icon(Icons.download),
                tooltip: 'Save PDF',
                onPressed: () async {
                  await Printing.sharePdf(
                    bytes: bytes,
                    filename: '$filename.pdf',
                  );
                },
              ),
            ],
          ),
          body: PdfPreview(
            build: (_) => bytes,
            canChangeOrientation: false,
            canDebug: false,
            pdfFileName: '$filename.pdf',
          ),
        ),
      ),
    );
  }
}
